apiVersion: v1
kind: Secret
metadata:
  name: "lldap-secret"
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "lldap-secret") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $jwtSecret := (get $secretData "lldap-jwt-secret") | default (randAlphaNum 32 | b64enc) }}
  {{- $userPassSecret := (get $secretData "lldap-ldap-user-pass") | default (randAlphaNum 32 | b64enc) }}
  lldap-jwt-secret: {{ $jwtSecret | quote }}
  lldap-ldap-user-pass: {{ $userPassSecret | quote }}

